me:
  email: email
hegdeflutes:
  email: email
server:
  port: 3000
  env: dev
mailjet:
  templates:
    contactme: 2278881
    hegdeflutescontactus: 2296585
  apikey:
    public: public
    private: private